version: '3'
services:
    terminal:
        stdin_open: true
        tty: true    
        build:
            context: ./docker/terminal
            dockerfile: Dockerfile
            args:
                APP_ENV: '${TERMINAL_ENV}'
                HOST_GID: '${HOST_TERMINAL_UID:-1000}'
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${TERMINAL_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${TERMINAL_HTTP_PORT:-3000}'
            HOST_TERMINAL_UID: '${HOST_TERMINAL_UID:-1000}'
            APP_ENV: '${TERMINAL_ENV}'
        ports:
            - '3000:3000'
        volumes:
            - './terminal:/var/www/html'
        networks:
            - nginx-proxy

    admin:
        stdin_open: true
        tty: true    
        build:
            context: ./docker/admin
            dockerfile: Dockerfile
            args:
                APP_ENV: '${ADMIN_ENV}'
                HOST_GID: '${HOST_ADMIN_UID:-1000}'
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${ADMIN_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${ADMIN_HTTP_PORT:-3000}'
            HOST_ADMIN_UID: '${HOST_ADMIN_UID:-1000}'
            APP_ENV: '${ADMIN_ENV}'
        volumes:
            - './admin:/var/www/html'
        networks:
            - nginx-proxy

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: '${TERMINAL_DOMAIN}'
            VIRTUAL_HTTP_PORT: '${NGINX_HTTP_PORT:-"80"}'
            VIRTUAL_HTTPS_PORT: '${NGINX_HTTPS_PORT:-"443"}'
            TERMINAL_DOMAIN: '${TERMINAL_DOMAIN:-realjournals.com}'
            ADMIN_DOMAIN: '${ADMIN_DOMAIN:-admin.realjournals.com}'
            NGINX_DEFAULT_TERMINAL_CONFIG: '${NGINX_DEFAULT_TERMINAL_CONFIG}'
            NGINX_DEFAULT_ADMIN_CONFIG: '${NGINX_DEFAULT_ADMIN_CONFIG}'
        ports:
            - '${NGINX_HTTP_PORT:-80}:${NGINX_HTTP_PORT:-80}'
            - '${NGINX_HTTPS_PORT:-443}:${NGINX_HTTPS_PORT:-443}'
        volumes:
            - '.:/var/www/html'
            - '${HOME}/www/certbot:/var/www/certbot'
            - '${HOME}/lib/letsencrypt:/var/lib/letsencrypt'
            - '${HOME}/letsencrypt:/etc/letsencrypt'
        networks:
            - nginx-proxy
        depends_on:
            - terminal
            - admin
        healthcheck:
            test: ["CMD-SHELL", "service nginx status || exit 1"]
networks:
    nginx-proxy:
        external: true
